spring.application.name=ticketguru

# h2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
# enables the logging of SQL statements
spring.jpa.show-sql=true
